language: python
python:
  - "3.4"
before_install:
    cd dragonsmash
install:
  - pip install -r requirements/travis.txt
before_script:
  - python manage.py makemigrations api # TODO: remove this once db migrations have been committed
script: coverage run --source='.' manage.py test --settings=config.settings.travis --noinput
after_success:
  - coverage report
